version: "3.9"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fastapi-network
    ports:
      - "5432:5432"

  fastapi-app:
    build: .
    container_name: fastapi-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app   # Mount local folder for hot-reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@postgres-db:5432/yourdb
    depends_on:
      - postgres-db
    networks:
      - fastapi-network

volumes:
  pgdata:

networks:
  fastapi-network:
    driver: bridge
